### PR TITLE
Feature/refactor

### PR DESCRIPTION
**Pull request by urscion**
Refactored the codebase to be a tad smaller/cleaner and understandable and to meet some python3 standards (`pathlib`, `mypy`, type hints, etc.)

Highlights:
* Caching is now delegated to classes
* Command line parsing uses argparse
* Attribute markers that force newlines are handled differently (e.g. %{prices.*})
* * Implemented via a global "sublines" list, reset prior to each card.
* Merged some implementation so all attribute resolution is centralized
* Removed the binary (should be added via the Releases feature of Github)
* Added a `requirements.txt`, `.gitignore` for Python, and a `scry.spec` file for building.

I did remove '^' from the attribute markers as I couldn't find a use case where '?' could not do the same thing. If there is a use case, please let me know!

Planning on adding some unit tests prior to submitting the PR.

### CODE REVIEW

**Comment by 0xdanelia** [comment]
Thank you for all of your effort.
This is a very large PR. It will take me a while to read over everything. I think it may be a simpler process if we divided the changes into separate PRs.
Also, the `*` attribute lists values while the `?` lists keys. For example:
`%{prices.?}`  -> 
```
['usd', 'usd_foil', 'eur', ...]
```
`%{prices.*}`  ->  
```
1.99
3.50
4.56
...
```
The intended use for `?` is as a debugging tool. While building a query, you can use it to list all of the attribute names available to you.

**Comment by urscion** [comment]
Ah sorry, I meant the difference between `?` vs. `^`. I updated the PR description to reflect this.

Yeah, all base functionality should be the same except for the removal of `^` I believe. If you have a suggestion for how to break them up, let me know. Otherwise, I can get around to that later this week.

**Comment by urscion** [comment]
Overall, I do like the design and the name is pretty cool too 👍 Was awesome for generating Scryfall CSVs :)

**Comment by 0xdanelia** [comment]
Thank you.

The `^` character displays the name of the previous parameter. So `%{hello.world.^}` will print out `world`.

This was intended to be used alongside `*` to display a parameter name next to its value. For example:

```
> scry lightning bolt --format='%{prices.*.^} %| %{prices.*}'
usd  2.18
eur  2.97
```

This differs from the `?` character, which lists all available parameters on a single line.

```
> scry lightning bolt --format='%{prices.?}'
['usd', 'usd_foil', 'usd_etched', 'eur', 'eur_foil', 'tix']
```

I think it would be more elegant if `?` were an iterative character just like `*` which could then be used to replace the `^` character. Something like:

```
> scry lightning bolt --format='%{prices.?}'
usd
usd_foil
usd_etched
eur
eur_foil
tix
```
```
> scry lightning bolt --format='%{prices.?} %| %{prices.*}'
usd  2.18
eur  2.97
```

**Comment by urscion** [comment]
Ahh, I think I understand. `?` prints available property names in a list format while `^` prints line-by-line?

Idk if it's an acceptable solution for you but I have a separate branch where instead of using a separate character of `^`, it allows the markers of `?-` and `*-` to print in a list format for property names and values, respectively.

**Comment by 0xdanelia** [comment]
I think just printing line-by-line is fine. If we wanted to format the output some other way (JSON, csv, etc) then I think a separate flag parameter would make more sense.

**Pull request closed without merging**
